### ISSUE TITLE
sasl log is not properly formatted

### ISSUE THREAD

**Issue by bullno1** [karlll/kjell#22]
Currently, messages from sasl get jumbled up.

**Comment by bullno1** [comment]
stdlib's error_logger_tty_h logs error like this:

```Erlang
io:format(user, "First line\nSecond line", []).
```

Output under kjell will be like this:

```sh
First line
             Second line
```

**Comment by karlll** [comment]
Yes, I can confirm that

```erlang
io:format(user,"First line\nSecond line",[])
```

gives the described behavior when

```erlang
io:format("First line\nSecond line",[])
```

..gives the expected result, i.e. carriage return + line feed.

**Comment by karlll** [comment]
I've studied the OTP code a bit, and it seems that the user_sup module registers the user process before the `k_user_drv:start_user/0` is able to.

Can you try starting kjell with the flag `-nouser` ?

**Comment by bullno1** [comment]
That seems to fix it.

**Comment by bullno1** [comment]
Since kjell has its own user process, is it safe to just add -nouser to bin/kjell?

**Comment by karlll** [comment]
I think so, let me try it out!

**Comment by karlll** [comment]
Did some quick testing and it seems to work ok with '-nouser'. Included in 9572c06.

**Comment by karlll** [comment]
Well, It seems like I was sloppy in verifying this fix. It doesn't work for me to add -nouser anymore. Apparently it did in March (as above), but not anymore, hangs instead. It might be OTP 18 I'm using now.

@bullno1 : Have you tested starting with -nouser on OTP 18 ?

**Comment by karlll** [comment]
Hi again! Please disregard the above! I was having some other changes in my branch which broke everything. Sorry :)

**Comment by essen** [comment]
Works for me, and you've been featured in http://erlang.mk/guide/ch14.html enjoy!

**Comment by karlll** [comment]
@essen: Awesome! Thanks!
