### ISSUE TITLE
non-interactive test

### ISSUE THREAD

**Issue by dunn** [karlll/kjell#25]
Is there any way to have kjell run a command or series of commands non-interactively, in order to test functionality? I'm trying to update the Homebrew formula and I can't figure out a test that the CI bots can run post-installation.

**Comment by karlll** [comment]
Hi!

That's great that you're updating the Homebrew formula!

Unfortunately I don't know any good way to test the installation in a non-interactive way. I will think about this, maybe if I could add some feature to run a sanity check given a command line parameter.

BTW, is the test in the current formula not working in the buildbot?
https://github.com/karlll/homebrew/blob/f4157b6492660ffbaefaa90aa269a2c7619d5a4e/Library/Formula/kjell.rb#L19-L21

... or do you want to add more ( and better) tests?

Thanks for contributing!

Wbr,

/Karl

**Comment by dunn** [comment]
The current test only works on the Mountain Lion bot; something must have changed between Ruby versions.

**Comment by karlll** [comment]
Ok! I'll see if I can add some sanity check that we could use.

**Comment by karlll** [comment]
Hi! I've added an non-interactive sanity check in #27 : 

  `$ kjell -sanity_check true`

.. will give a non-zero exit value if everything is fine. I add this in the homebrew formula.

**Comment by dunn** [comment]
Thanks!

**Comment by dunn** [comment]
Opened a PR: https://github.com/Homebrew/homebrew/pull/41645

**Comment by optikfluffel** [comment]
@dunn I'm sure you noticed but your [PR didn't pass the tests](http://bot.brew.sh/job/Homebrew%20Pull%20Requests/29485/).
