### ISSUE TITLE
Upgrade to OTP 18.0

### ISSUE THREAD

**Issue by tyre** [karlll/kjell#26]
In order to upgrade the homebrew erlang otp version (https://github.com/Homebrew/homebrew/pull/41035), we need to get kjell working in 18.0.

Are you able to make the changes?

Thanks!

**Comment by karlll** [comment]
Hi! Thanks for letting me know!

I will spend some time the coming week to do an uplift.

**Comment by karlll** [comment]
@tyre: I've manually verified that kjell will run on the latest OTP version, but I don't really know how to see the formula issue. Is there any build logs I can look at? Thanks!

**Comment by optikfluffel** [comment]
Are the failing tests in #25 a problem here?

**Comment by karlll** [comment]
As far as I know, there should be no failing test using the latest commit in https://github.com/Homebrew/homebrew/pull/41645

**Comment by optikfluffel** [comment]
Cool :+1:
